### ISSUE TITLE
Product website / Repo

### ISSUE THREAD

**Issue by mchapman** [kakoni/awesome-healthcare#1]
Thanks for all the work collating all that.  It wasn't clear whether you were inviting discussion here on in openhealthhub - hope you don't mind me doing it here.

I would favour having up to two links per product: one to the repo and (optionally) one to the main product website.  But when I tried to start doing the research I soon found that it was difficult, as not all product websites have links to the source code repo.  Which then begs the question : in what sense are they open?

Would welcome views, and am prepared to do some of the leg work when clarity emerges.

**Comment by kakoni** [comment]
Having seperate links does make sense. I'll start the work for it;)

And to your question about openness, if there isnt source repo/clear licence/community I wouldnt consider it "open". For instance, what do you think about this http://www.openempi.org/

**Comment by mchapman** [comment]
Well I can't find any links to a repo.  There is a news item about an AMI, and if you dug around in there you _may_ find some source code?  But I wouldn't include it in the list I think.  As to your criteria I would agree with the first 2 (repo / open source licence) for inclusion, and publish some metric(s) on the community, but a community should not be a pre-requisite in my opinion.

**Comment by MatthewVita** [comment]
@mchapman I'm not sure we need multiple links per entry because:

1) This is not a pattern with the various `awesome-` repos on Github
2) It may be easy to find the project page/user documentation for a given project

Feel free to refute these points. I'm not 100% on one side.

@kakoni I just entered https://kenai.com/jira/browse/OPENEMPI-92 for OpenEMPI. Hoping they address this because it's a neat project.

Thanks,
Matthew

**Comment by kakoni** [comment]
Agree with @MatthewVita, we'll continue with the familar awesome- repo format.

**Comment by MatthewVita** [comment]
Just so this doesn't seem subjective: I put in a pull request to the master awesome repo. They have _very_ specific criteria for lists and one of those items is _one_ link per entry.
