### ISSUE TITLE
VistA & OpenEP

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#15]
- VistA's site https://connectedcare.va.gov/VistA.asp is down. I have contacted ConnectedCare, put a notice on the Wikipedia entry for VistA, and temporarily switched out this repo's link to use a popular fork of VistA: https://www.osehra.org/content/osehra-vista. Hope CC works this out!

- OpenEP has been wiped from the ehrscape website. I have updated this repo to link to https://github.com/ehrscape/examples/tree/master/openep. We need to make sure this project is still active/code actually runs, otherwise it should be removed. Any takers?

**Comment by kakoni** [comment]
Regarding OpenEP, I'll contact marand and ask.

**Comment by MatthewVita** [comment]
Thanks @kakoni 

I hope CC gets back to me or, simply, fixes the issue!

**Comment by MatthewVita** [comment]
@kakoni any updates?

**Comment by kakoni** [comment]
Not yet. Contacting code4health team also.

**Comment by kakoni** [comment]
Closing old issues.
