### ISSUE TITLE
OpenEMPI

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#20]
Although this is in our list, I really think following up with OpenEMPI would be good for the larger open healthcare community.

For context, I haven't received any updates on https://kenai.com/jira/browse/OPENEMPI-92

I'm now questioning if the project is being maintained:

![image](https://cloud.githubusercontent.com/assets/1715206/24824525/ec561bf4-1bda-11e7-831c-3ebc90fa4d32.png)

I'm not necessarily volunteering to be the new maintainer as I have my hands full with OpenEMR, however, I would like to get an answer because I'm sure we can advertise this on HackerNews/Reddit and get a proper maintainer.

**Comment by MatthewVita** [comment]
Haven't heard back. Very upsetting :(

**Comment by MatthewVita** [comment]
I am incredibly persistent :). I just hope someone gets back to me.

![f](https://cloud.githubusercontent.com/assets/1715206/26149965/69cbc5e4-3aca-11e7-9fae-812837fc6d96.png)

**Comment by MatthewVita** [comment]
...and yes, you are reading that right. The issue tracker they used has ceased operations.

**Comment by MatthewVita** [comment]
Okay, I heard back. They are no longer open source :(

**Comment by eric-jahn** [comment]
Do they have a closed source product, and where is the latest OpenEMPI code posted?  I see this: https://github.com/anznpatel/openempi , but it is v3.1.0, and v3.5.3 seems like the latest before maintenance ended.
