### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#21]
Per https://github.com/sindresorhus/awesome/pull/925#issuecomment-293004190, we need to add `awesome-list`, `awesome`, and `list` topics to this repo to be compliant.

**Comment by MatthewVita** [comment]
@kakoni, please tackle this and I'll tackle the other item in the issue. Thanks.

**Comment by kakoni** [comment]
@MatthewVita Topics added!

**Comment by MatthewVita** [comment]
Thanks!
