### ISSUE TITLE
FreeMedForms Website issue

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#24]
https://freemedforms.com/ isn't working for me... anyone else?

**Comment by sanjayankur31** [comment]
Seems to be working here:

https://freemedforms.com/

https://freemedforms.com/en/start?animal=fmf

**Comment by MatthewVita** [comment]
![image](https://cloud.githubusercontent.com/assets/1715206/25066049/28254844-21e9-11e7-8da7-5eb0c8952bc9.png)

**Comment by MatthewVita** [comment]
Works on Firefox though...

**Comment by MatthewVita** [comment]
Just emailed them... hoping they fix it!
