### ISSUE TITLE
online diagnosis tools (symptom checkers)

### ISSUE THREAD

**Issue by KiaraGrouwstra** [kakoni/awesome-healthcare#25]
No clue if these are in scope here, you decide. :)

- http://symptoms.webmd.com/default.htm
- https://symptomchecker.isabelhealthcare.com/suggest_diagnoses_advanced/landing_page

**Comment by MatthewVita** [comment]
Hi @tycho01,

I would love to list these, but unfortunately they are not open source :(

I appreciate you submitting this, however!

**Comment by KiaraGrouwstra** [comment]
Fair enough -- definitely sounds like a... 'market' opportunity!
