### ISSUE TITLE
Merge with Wikipedia's page?

### ISSUE THREAD

**Issue by jsonin** [kakoni/awesome-healthcare#26]
Good list!
When's the merge to https://en.wikipedia.org/wiki/List_of_open-source_health_software ?
This belongs on a bigger stage.

**Comment by MatthewVita** [comment]
@jsonin: oh wow, great idea!

@kakoni: we should make it a point to stay in sync with this Wikipedia page. Do you agree that this is a great idea? If so, I am happy to sync the pages.

**Comment by jsonin** [comment]
I started to seed the Specifications into Wikipedia.
Already they dropped 2 (SHR + SMART on FHIR) because of notability guidelines. Uggh. So I understand the reason of posting here vs fighting the politics of WP. But they are a primary reference and sometimes its worth the initial skirmish.

**Comment by MatthewVita** [comment]
Good point, I don't think the pages will be 100% in sync because of WP's requirements (which, in all honesty, I'm not against).

Even at 80% parity, I'm happy.

**Comment by kakoni** [comment]
@MatthewVita go ahead!

**Comment by MatthewVita** [comment]
I'm about halfway done with this work! Going to be updating this repo and the Wikipedia shortly.

UPDATE: This took hours (combed through each project to make sure it is active and provides value - lots of stuff checked in!). I'm going to update the Wikipedia page now!

**Comment by MatthewVita** [comment]
NOTE: I simply added this section to the talk page https://en.wikipedia.org/wiki/Talk:List_of_open-source_health_software#Proposal_for_empty_links

None of the mergable links have WP pages

**Comment by jsonin** [comment]
Thanks Matt.
That's a bunch of work!
Notice the radio silence in the WP talk, vs immediate deletion. This is what drives me nuts about WP...

**Comment by MatthewVita** [comment]
Hi @jsonin, to be fair, each WP page is different (ran by different people), but I do get your frustration. If I don't hear back soon, I will simply apply the revisions :).

**Comment by MatthewVita** [comment]
Do you think I should insert empty links or external links? Don't want to cause _too_ much friction.

**Comment by MatthewVita** [comment]
For anyone interested, I've went ahead and added a whole bunch of empty links to the Wikipedia page. For full context, please see the following: https://en.wikipedia.org/wiki/Talk:List_of_open-source_health_software#Filling_in_gaps

:)

**Comment by jsonin** [comment]
Thanks Matt for your persistence.
WP is one weird organism. 
Oh yeah, it's run by humans.

**Comment by MatthewVita** [comment]
To be honest, it was the maintainers of the projects that were not very responsive.

In addition to WP, open source is one weird organism.
Oh yeah, it's run by humans.

:)
