### ISSUE TITLE
Glucosio

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#31]
Determine if http://www.glucosio.org/ project is active and provides value. Add to list if both of those items check out.

**Comment by kakoni** [comment]
Look pretty active (based on github).
While on the topic (diabetes), we should also add http://www.nightscout.info, https://github.com/timomer/HAPP, lhttps://github.com/LoopKit/Loop,

**Comment by kakoni** [comment]
Closing old issues.
