### ISSUE TITLE
support Chinese

### ISSUE THREAD

**Issue by MarielMa** [kakoni/awesome-healthcare#51]
Does it support chinese EHR?

**Comment by MatthewVita** [comment]
@MarielMa Hello - does the software support multiple languages? Thanks.

@kakoni's Would like your take on possibly having an "International Software" section if this is a good addition, but is limited in language support - not sure how to go about labeling this.

**Comment by kakoni** [comment]
Closing this for now. Lets rethink about this if needed in the future.
