### ISSUE TITLE
EHR hyperlinks errors. Request to update these hyperlinks. 

### ISSUE THREAD

**Issue by SherylGit** [kakoni/awesome-healthcare#53]
Not working hyperlinks:
[EHR/Ripple hyperlink] (http://rippleosi.org/)
[EHR/VistA hyperlink] (https://osehra.org/content/osehra-vista)

Change request: 

`*[Ripple OSI](https://www.openhealthhub.org/t/healthcare-driven-by-open-source-software-ripple-osi/) -  NHS funded community-led initiative towards an integrated Digital Care Record Platform.`

`*[VistA](http://worldvista.org/AboutVistA) - Health Information Technology System.`

Test and approval request.

**Comment by MatthewVita** [comment]
Hi @SherylGit,

Good find. Can you put a pull request in that removes VistA (OSEHRA has closed down) and updates Ripple with this link: https://ripple.foundation/

Thanks!

**Comment by SherylGit** [comment]
Hi 

Thanks. I removed Epic, Cerner , and VistA links, and update Ripple link. 

Another finding is that there are some closed links or timeout happens in requests (I add git CI with one test_script.py to do urls validation):
http://www.cottagemed.org/cottage-med
http://www.openeobs.org
http://sf.anu.edu.au/Vizlab/drishti/
http://www.endrov.net/
https://www.mirth.com
https://www.ihris.org/toolkit/

Please check. If these urls will be updated, I will do one pull request for updating urls. 

Cheers

SherylGit

**Comment by MatthewVita** [comment]
Great PR - I just merged it. Thanks!
