### ISSUE TITLE
Add Epic and Cerner in EHR

### ISSUE THREAD

**Issue by SherylGit** [kakoni/awesome-healthcare#54]
Cerner and Epic are both makers of health information technology and electronic health record (EHR) software and are the biggest EMR vendors.

```
* [Epic](https://www.epic.com/software) - One marker of health information technology and EHR.
  
* [Cerner](https://www.cerner.com/) - Another marker of health information technology and EHR.
```

Test and approval request.

**Comment by MatthewVita** [comment]
Hi @SherylGit,

Thanks for posting this. I agree that these two vendors have a **lot** of leverage in many hospital systems. However, these systems are not open source software (need for the list).

I'll leave this issue open to see if you would like to point out any useful open source tools either company have recently created that we can consider.

Thanks!

**Comment by MatthewVita** [comment]
We're on the same page now with your PR - thanks again
