### ISSUE TITLE
MUMPS/ANSI M based systems

### ISSUE THREAD

**Issue by rochus-keller** [kakoni/awesome-healthcare#59]
Good idea, useful list, thanks. Maybe you also want to consider systems like VISTA or RPMS (see e.g. http://www.vistapedia.com/index.php/Main_Page). It is or was also used in your country, see https://en.wikipedia.org/wiki/VistA; do you have information whether it's still in use there?

**Comment by kakoni** [comment]
@rochus-keller Thank you for the suggestion. Few points
1) Worldvista homepage seems to be down? http://worldvista.org
1) Openvista site seems to be under redesign? https://medsphere.org

It feels like development on these projects has stalled?

**Comment by rochus-keller** [comment]
There were a lot of changes during the last four years. Don't know what the status of each EHR implementation is today, but the web sites are still accessible by archive.org:

https://web.archive.org/web/20160411190730/http://www.worldvista.org/

https://web.archive.org/web/20160307175023/http://medsphere.com/

https://web.archive.org/web/20060927112529/http://www.ehr.ihs.gov/

and there is still the active Github repository: https://github.com/WorldVistA

https://www.linkedin.com/company/osehra/ states that they closed down in 2020 and lists some references
