### ISSUE TITLE
Add an app

### ISSUE THREAD

**Issue by ghost** [kakoni/awesome-healthcare#71]
You could add this open source 3D atlas of anatomy:
https://www.z-anatomy.com/

**Comment by programmers** [comment]
Hi @Melodicpinpon,

Thanks for this. It looks very useful.

All appear to be using very open CC licenses (including model/data files), but I can't find any public source code for the actual app (web or mobile viewers). Please let me know where I can find those.

Thanks,
Matthew

**Comment by MatthewVita** [comment]
Hi @Melodicpinpon 

Thanks for this. It looks very useful.

All appear to be using very open CC licenses (including model/data files), but I can't find any public source code for the actual app (web or mobile viewers). Please let me know where I can find those.

Thanks,
Matthew

**Comment by ghost** [comment]
Good morning Matthew,

Here is the code of the app:
https://github.com/LluisV/Z-Anatomy

If you know people who may be willing to join their efforts to improve this
open source tool, please let them know that they are welcome:
https://www.z-anatomy.com/forum/about-the-project/contributors-homepage

Have a nice day,

Gauthier

Le mer. 19 oct. 2022 à 05:19, programmers ***@***.***> a
écrit :

**Comment by MatthewVita** [comment]
Hi @Melodicpinpon,

Thank you so much for that information. I just have 2 more questions before we include this!

1. I noticed on the Github that this is licensed as GPL-3.0 ** - isn't the project/models all CC?
2. I can't find the instructions on building (or just running) the app... are they somewhere on the project website?

** https://github.com/LluisV/Z-Anatomy/blob/main/LICENSE

Thanks,
Matthew

**Comment by ghost** [comment]
Hi Matthew,

1:I am not expert in licenses and, as the founder and 3D modeler of the
project, I naturally copied and updated the existing licenses of the source
model (BodyPArts3D) into CC-VBY-SA 4.0.
I 'll study further the subtilities of the GPL-3.0. At first glance, it
seems to be another kind of CC license (and to require attribution, if any).
I'll see with Lluis, the developer, if he had something in mind for
prefering GPL3 over CC-BY-SA 4.0.

2:There is no documentation but if you just run the program for the first
time, or go in the help panel, you will find all the instructions about how
to use the software and its shortcuts.

Sincerely,

Gauthier

**Comment by MatthewVita** [comment]
Hi @Melodicpinpon,

Hope you are well.

1. Cool. It's definitely worth looking into - they have some capability as far as I can tell. I'm more aware of the GPL side of things, however. Let me know!

2. When we get the PR going, we'll link to your website instead of the Github repo.

Much appreciated - cool project!

Thanks,
Matthew

**Comment by kakoni** [comment]
Added!
