### ISSUE TITLE
Additional Maintainer

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#8]
@kakoni,

I really like the spirit of this repository. It's very unique and helpful.

I want to offer my help in being an additional maintainer of this project. I noticed that recent PRs/issues haven't been addressed in a timely way.

Feel free to make me an owner (you can trust me) so that I can run the project with you.

Thanks,
Matthew

**Comment by kakoni** [comment]
Hi @MatthewVita! Hmm, had some issues with notifications, so didnt notice recent pr's.
Anyway, additional pair of hands sounds wonderful, so I added you as a contributor.

Cheers,
Karri

**Comment by MatthewVita** [comment]
Thanks!
