### ISSUE TITLE
Enterprise Master Patient Index

### ISSUE THREAD

**Issue by MatthewVita** [kakoni/awesome-healthcare#9]
We can benefit from an EMPI section. Here are the two solutions I am aware of:

- https://mediccr.codeplex.com/ (can anyone vouch for this)
- https://svn.kenai.com/svn/openempi~source-repository/trunk/

That that OpenEMPI can't be added until this ticket: https://kenai.com/jira/browse/OPENEMPI-92 is resolved.

Thanks,
Matthew

**Comment by kakoni** [comment]
Wonder where mediccr is going to move since codeplex is going down?

**Comment by MatthewVita** [comment]
Just saw that announcement yesterday. They have until December to figure it out, to be fair.

**Comment by kakoni** [comment]
Anyway, they seem to be active, so looks good.

**Comment by MatthewVita** [comment]
@kakoni I just checked in https://github.com/kakoni/awesome-health/pull/19

It doesn't seem like OpenEMPI is very responsive. I included them in our list, but I am not happy that they didn't get back to me :(

**Comment by MatthewVita** [comment]
Regardless, they have a rather mature solution and the source code is out there. Don't want to omit them. I will try emailing the support email to get the ball rolling.
